# Generated by Django 5.1.1 on 2025-08-13 18:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('food_items', models.JSONField(default=list, help_text='List of dicts with food_id, quantity, and unit')),
                ('total_calories', models.FloatField(blank=True, null=True)),
                ('total_weight_grams', models.FloatField(blank=True, null=True)),
                ('nutrient_profile', models.JSONField(blank=True, default=dict)),
                ('fcs_score', models.FloatField(blank=True, null=True)),
                ('hefi_score', models.FloatField(blank=True, null=True)),
                ('hsr_score', models.FloatField(blank=True, null=True)),
                ('heni_score', models.FloatField(blank=True, null=True)),
                ('environmental_impact', models.JSONField(blank=True, default=dict)),
                ('sustainability_score', models.FloatField(blank=True, null=True)),
                ('carbon_footprint', models.FloatField(blank=True, null=True)),
                ('preparation_time', models.PositiveIntegerField(blank=True, help_text='Minutes', null=True)),
                ('cooking_time', models.PositiveIntegerField(blank=True, help_text='Minutes', null=True)),
                ('servings', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('tips', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meal_images/')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'meals_meal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Meal Categories',
                'db_table': 'meals_category',
            },
        ),
        migrations.CreateModel(
            name='MealCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collection_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meals_collection',
            },
        ),
        migrations.CreateModel(
            name='MealCollectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meals_collection_item',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MealComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meals_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meals_like',
            },
        ),
        migrations.CreateModel(
            name='MealRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taste_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('health_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ease_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sustainability_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meals_rating',
            },
        ),
        migrations.CreateModel(
            name='MealSave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meals_save',
            },
        ),
    ]
