# Generated by Django 5.1.1 on 2025-08-13 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meals.mealcategory'),
        ),
        migrations.AddField(
            model_name='mealcollection',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealcollectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mealcollection'),
        ),
        migrations.AddField(
            model_name='mealcollectionitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
        migrations.AddField(
            model_name='mealcollection',
            name='meals',
            field=models.ManyToManyField(through='meals.MealCollectionItem', to='meals.meal'),
        ),
        migrations.AddField(
            model_name='mealcomment',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meals.meal'),
        ),
        migrations.AddField(
            model_name='mealcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='meals.mealcomment'),
        ),
        migrations.AddField(
            model_name='mealcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meallike',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='meals.meal'),
        ),
        migrations.AddField(
            model_name='meallike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealrating',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='meals.meal'),
        ),
        migrations.AddField(
            model_name='mealrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealsave',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='meals.meal'),
        ),
        migrations.AddField(
            model_name='mealsave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['creator', 'is_public'], name='meals_meal_creator_6c4b89_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['meal_type'], name='meals_meal_meal_ty_9f3559_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['category'], name='meals_meal_categor_5c18c6_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['-created_at'], name='meals_meal_created_3fc47a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mealcollection',
            unique_together={('creator', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='meallike',
            unique_together={('user', 'meal')},
        ),
        migrations.AlterUniqueTogether(
            name='mealrating',
            unique_together={('user', 'meal')},
        ),
        migrations.AlterUniqueTogether(
            name='mealsave',
            unique_together={('user', 'meal')},
        ),
    ]
